# Generated by Django 2.2.1 on 2019-05-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False, verbose_name='가수코드')),
                ('name', models.TextField(verbose_name='가수명')),
                ('debut', models.DateField(verbose_name='데뷔년도')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='예매일시')),
                ('coin', models.IntegerField(verbose_name='사용연료')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='공연코드')),
                ('name', models.TextField(verbose_name='공연이름')),
                ('genre', models.CharField(choices=[('락/메탈', '락/메탈'), ('발라드/R&B', '발라드/R&B'), ('일렉트로니카', '일렉트로니카'), ('댄스', '댄스'), ('포크', '포크'), ('트로트', '트로트'), ('힙합/랩', '힙합/랩'), ('크로스오버', '크로스오버'), ('뉴에이지', '뉴에이지'), ('클럽뮤직', '클럽뮤직'), ('재즈/블루스', '재즈/블루스'), ('J-POP', 'J-POP'), ('콘서트', '콘서트'), ('탱고', '탱고'), ('내한공연', '내한공연'), ('개그콘서트', '개그콘서트')], max_length=7, verbose_name='공연장르')),
                ('rating', models.TextField(verbose_name='관람등급')),
                ('poster', models.ImageField(upload_to='', verbose_name='공연포스터')),
                ('description', models.TextField(verbose_name='공연설명')),
                ('date', models.DateTimeField(verbose_name='관람시간')),
                ('status', models.CharField(choices=[('진행', '진행'), ('예정', '예정'), ('종료', '종료')], max_length=2, verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='FArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='FConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Artist')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Concert')),
            ],
            options={
                'unique_together': {('artist', 'concert')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(verbose_name='좌석구역')),
                ('seat_num', models.TextField(verbose_name='좌석번호')),
                ('cost', models.TextField(verbose_name='티켓값')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Concert')),
            ],
            options={
                'unique_together': {('concert', 'section', 'seat_num')},
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='주최사코드')),
                ('name', models.TextField(verbose_name='주최사명')),
                ('si', models.TextField(verbose_name='시')),
                ('gu_dong', models.TextField(verbose_name='구, 동')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('homepage', models.URLField(verbose_name='홈페이지주소')),
                ('contact', models.CharField(max_length=11, verbose_name='연락처')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='이메일')),
                ('password', models.CharField(help_text='최대 12자리입니다.', max_length=12, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=5, verbose_name='이름')),
                ('sex', models.CharField(choices=[('여성', 'female'), ('남성', 'male'), ('그외', 'other')], max_length=2, verbose_name='성별')),
                ('contact', models.CharField(max_length=11, verbose_name='연락처')),
                ('coin', models.IntegerField(verbose_name='연료')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.Concert')),
                ('date', models.DateField(verbose_name='공연날짜')),
                ('time', models.TimeField(verbose_name='공연시간')),
            ],
        ),
        migrations.AddField(
            model_name='fconcert',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.User'),
        ),
        migrations.AddField(
            model_name='fartist',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.User'),
        ),
        migrations.AddField(
            model_name='concert',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Sponsor'),
        ),
        migrations.AddField(
            model_name='book',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Concert'),
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.User'),
        ),
        migrations.AlterUniqueTogether(
            name='fconcert',
            unique_together={('email', 'concert')},
        ),
        migrations.AlterUniqueTogether(
            name='fartist',
            unique_together={('email', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('email', 'artist')},
        ),
    ]
