# Generated by Django 2.2.1 on 2019-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190528_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.PositiveIntegerField(default=0, verbose_name='연료'),
        ),
    ]
