# Generated by Django 2.2.1 on 2019-05-31 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190528_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='공연날짜')),
                ('time', models.DateTimeField(verbose_name='공연시간')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=0, verbose_name='좌석번호'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(default='N/A', verbose_name='공연설명'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('concert', 'section')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_num',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(verbose_name='좌석구역')),
                ('price', models.IntegerField(default=0, verbose_name='티켓값')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Concert')),
            ],
            options={
                'unique_together': {('concert', 'section')},
            },
        ),
    ]
